//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18046
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agente.TimeService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.Nanonull.com/TimeService/", ConfigurationName="TimeService.TimeServiceSoap")]
    public interface TimeServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Nanonull.com/TimeService/getUTCTime", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string getUTCTime();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Nanonull.com/TimeService/getOffesetUTCTime", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string getOffesetUTCTime(double hoursOffset);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Nanonull.com/TimeService/getServerTime", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string getServerTime();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Nanonull.com/TimeService/getServerTimeZone", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string getServerTimeZone();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Nanonull.com/TimeService/getServerCity", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string getServerCity();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Nanonull.com/TimeService/getTimeZoneTime", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string getTimeZoneTime(string timezone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Nanonull.com/TimeService/getCityTime", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string getCityTime(string city);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TimeServiceSoapChannel : Agente.TimeService.TimeServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TimeServiceSoapClient : System.ServiceModel.ClientBase<Agente.TimeService.TimeServiceSoap>, Agente.TimeService.TimeServiceSoap {
        
        public TimeServiceSoapClient() {
        }
        
        public TimeServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TimeServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TimeServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TimeServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string getUTCTime() {
            return base.Channel.getUTCTime();
        }
        
        public string getOffesetUTCTime(double hoursOffset) {
            return base.Channel.getOffesetUTCTime(hoursOffset);
        }
        
        public string getServerTime() {
            return base.Channel.getServerTime();
        }
        
        public string getServerTimeZone() {
            return base.Channel.getServerTimeZone();
        }
        
        public string getServerCity() {
            return base.Channel.getServerCity();
        }
        
        public string getTimeZoneTime(string timezone) {
            return base.Channel.getTimeZoneTime(timezone);
        }
        
        public string getCityTime(string city) {
            return base.Channel.getCityTime(city);
        }
    }
}
